name: Deployment to production Environment

on:
  release:

jobs:
  build_and_deploy_functions:
    runs-on: ubuntu-latest
    name: Build and Deploy Function Backend
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
    #ToDo: Add Actions for Function

  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: "__"
          tokenSuffix: "__"
          files: AbeckDev.Dlrgdd.RegistrationTool.Frontend/wwwroot/appsettings.json
        env:
          FunctionEndpoint: "https://jhvregistrationfunctions.azurewebsites.net/api/"
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_CLIFF_033C84C03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/AbeckDev.Dlrgdd.RegistrationTool.Frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations #####
